[build-system]
requires = [
    "setuptools==80.9.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "docassemble.DeAhcd"
version = "1.0"
description = "DE AHCD"
readme = "README.md"
authors = [
    { name = "Jason Stoehr", email = "jstoehr@declasi.org" },
]
dependencies = [
    "docassemble.ALWeaver @ git+https://github.com/SuffolkLITLab/docassemble-ALWeaver.git@main",
    "docassemble.AssemblyLine @ git+https://github.com/SuffolkLITLab/docassemble-AssemblyLine.git@main",
]
license = "MIT"
license-files = [
    "LICENSE",
]

[project.urls]
Homepage = "https://courtformsonline.org"

[tool.setuptools.packages.find]
where = [
    ".",
]
